spring:
  application:
    name: api-concurrency
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.237.66:3306/paas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
     hibernate:
       hbm2ddl:
          auto: update